# Generated by Django 2.2.4 on 2020-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.PositiveIntegerField()),
                ('from_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('to_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=5)),
                ('from_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('to_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('no_of_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
