# Generated by Django 2.2.4 on 2020-08-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
