# Generated by Django 2.2.4 on 2020-08-26 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
                ('from_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('to_city', models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'ManasaKonko'), ('BS', 'Bansang')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
