# Generated by Django 2.2.4 on 2020-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='from_city',
            field=models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'MansaKonko'), ('BS', 'Bansang')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='to_city',
            field=models.CharField(choices=[('KF', 'Kanifing'), ('BR', 'Brikama'), ('BJ', 'Banjul'), ('SK', 'Serrekunda'), ('BA', 'Basse'), ('SM', 'Soma'), ('KR', 'Kaur'), ('FF', 'Farafenni'), ('KW', 'Kerewan'), ('FT', 'Fototo'), ('AL', 'Amdalai'), ('BAA', 'Bara'), ('MK', 'MansaKonko'), ('BS', 'Bansang')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
