# Generated by Django 2.2.4 on 2020-08-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200827_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
